create schema TIMER;

CREATE TABLE "TIMER"."CLOCK"
(
   TMR_ID bigint PRIMARY KEY NOT NULL,
   AUD_CREATE timestamp,
   AUD_UPDATE timestamp,
   TMR_DH_TIMER timestamp,
   USER_USR_PIS bigint
)
;
CREATE TABLE "TIMER"."USER"
(
   USR_PIS bigint PRIMARY KEY NOT NULL,
   AUD_CREATE timestamp,
   AUD_UPDATE timestamp,
   USR_NM varchar(100),
   USR_PW varchar(1000)
)
;
ALTER TABLE "TIMER"."CLOCK"
ADD CONSTRAINT FK1REV8ERGBWNQRX62RFST6C56L
FOREIGN KEY (USER_USR_PIS)
REFERENCES "TIMER"."USER"(USR_PIS)
;
CREATE INDEX SYS_IDX_FK1REV8ERGBWNQRX62RFST6C56L_10163 ON "TIMER"."CLOCK"(USER_USR_PIS)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10156_10157 ON "TIMER"."CLOCK"(TMR_ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10159_10160 ON "TIMER"."USER"(USR_PIS)
;
