version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: 
      - mysql-entrypoint.sh
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user
  user-service:
    image: manorfm/user-service:latest
    container_name: user-service
    build: ./users-service/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - gateway-service
      - mysql
  clicks-service:
    image: manorfm/clicks-service:latest
    container_name: clicks-service
    build: ./clicks-service/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - user-service
  gateway-service:
    image: manorfm/gateway-service:latest
    container_name: gateway-service
    build: ./gateway-service/Dockerfile
    ports:
      - 80:80
    depends_on:
      - discovery-service
  discovery-service:
    image: manorfm/discovery-service:latest
    container_name: discovery-service
    build: ./discovery-service/Dockerfile
    ports:
      - 8700:8700
  zipkin-service:
    image: manorfm/discovery-service:latest
    container_name: discovery-service
    build: ./discovery-service/Dockerfile
    ports:
      - 8700:8700
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  logstash:
    image: logstash
    container_name: logstash
    ports:
      - 5001:5000
    environment:
      - 'input { tcp { port => 5001 codec => "json" } } output { elasticsearch { hosts => ["192.168.10.1"] index => "micro-%{serviceName}"} }'
    depends_on:
      - kibana
