info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    users: 
      path: /users/**
      serviceId: user-service
    clicks: 
      path: /clicks/**
      serviceId: click-service
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 80000

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery-service:8700}/eureka/
##defaultZone: http://localhost:8700/eureka/
    registerWithEureka: false
      
server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
