server:  
  port: ${PORT:8700}
    
eureka:  
  instance:
##hostname: localhost
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  